name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Setup Java JDK
        uses: actions/setup-java@v2.1.0
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Setup Chrome driver
        uses: nanasess/setup-chromedriver@v1.0.1
      - name: Cache SonarCloud packages
        uses: actions/cache@v2.1.6
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Gradle packages
        uses: actions/cache@v2.1.6
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      #- name: Setup tmate session
      #  uses: mxschmitt/action-tmate@v3
      - name: Build with Gradle and analyze with Sonarqube
        run: |
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac $DISPLAY -screen 0 1920x1080x24 > /dev/null 2>&1 &
          ./gradlew build
      #    ./gradlew sonarqube                                              # Uncomment this line if you have to analyze with sonarcloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}                          # Uncomment this line if you have to analyze with sonarcloud and add the SONAR_TOKEN in the secrets
          DISPLAY: :99
